//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace invCruzRoja.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVENTARIO
    {
        public int IDInventario { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public string NumSerie { get; set; }
        public string Estado { get; set; }
        public Nullable<int> IDEmpleado { get; set; }
        public Nullable<int> IDTerritorio { get; set; }
        public Nullable<System.DateTime> FechaAsignado { get; set; }
        public Nullable<System.DateTime> FechaRetiro { get; set; }
        public string Descripcion { get; set; }
        public string TipoActivo { get; set; }
        public string MACAddress { get; set; }
        public string Propietario { get; set; }
    
        public virtual PERSONAS PERSONAS { get; set; }
        public virtual TERRITORIOS TERRITORIOS { get; set; }
    }
}
