//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventariosCRC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVENTARIO
    {
        public int IDInventario { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public string NumSerie { get; set; }
        public string Estado { get; set; }
        public Nullable<int> IDEmpleado { get; set; }
        public Nullable<int> IDTerritorio { get; set; }
        public Nullable<System.DateTime> FechaAsignado { get; set; }
        public Nullable<System.DateTime> FechaRetiro { get; set; }
        public string Descripcion { get; set; }
        public string TipoActivo { get; set; }
        public string MACAddress { get; set; }
        public string Propietario { get; set; }
    
        public virtual PERSONA PERSONA { get; set; }
        public virtual TERRITORIO TERRITORIO { get; set; }
    }
}
